#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'controller==0.0.0','console_scripts','controller'
__requires__ = 'controller==0.0.0'
import re
import sys
from pkg_resources import load_entry_point
from controller import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    main()
